table 'Agent jobs - list'
	lineageTag: 7b08474b-4299-4d9e-8dbf-84f60144c13f

	column Job
		dataType: string
		lineageTag: 1af15eb6-8d53-4e1c-9542-7b9387b1921b
		summarizeBy: none
		sourceColumn: Job

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 877db0e0-1074-4bfb-9f07-20ff5793725f
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'Job enabled'
		dataType: string
		lineageTag: 0fbbefa6-4463-4a91-b8b1-bc0c3f77dc8f
		summarizeBy: none
		sourceColumn: Job enabled

		annotation SummarizationSetBy = Automatic

	column 'Schedule enabled'
		dataType: string
		lineageTag: 4628f573-56f1-411d-b3a7-d956704242ad
		summarizeBy: none
		sourceColumn: Schedule enabled

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 32e544ec-b478-4b5e-aa53-211d0eae3648
		summarizeBy: none
		sourceColumn: Timestamp

		annotation SummarizationSetBy = Automatic

	partition 'Agent jobs - list' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Agent jobs configuration")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Agent jobs - list"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  selectColumns = Table.SelectColumns(
				    datasetToUse, 
				    {
				      "JobEnabledTxt", 
				      "JobName", 
				      "ScheduleEnabledTxt", 
				      "Timestamp", 
				      "TotalDesc"
				    }
				  ), 
				  renamedColumns = Table.RenameColumns(
				    selectColumns, 
				    {
				      {"JobEnabledTxt", "Job enabled"}, 
				      {"JobName", "Job"}, 
				      {"ScheduleEnabledTxt", "Schedule enabled"}, 
				      {"TotalDesc", "Description"}
				    }
				  )
				in
				  renamedColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

