table 'Allocation units'
	lineageTag: 4e2ac486-e35c-4567-8fa5-f26187c20533

	column 'Partition no.'
		dataType: int64
		formatString: #,0
		lineageTag: b1a9dde0-05d3-45ae-bec2-e1a5981142c6
		summarizeBy: none
		sourceColumn: Partition no.

		annotation SummarizationSetBy = User

	column 'Allocation unit type'
		dataType: string
		lineageTag: dbb64d2f-f688-4869-bba2-e8894499a2f9
		summarizeBy: none
		sourceColumn: Allocation unit type

		annotation SummarizationSetBy = Automatic

	column TotalSpaceKB
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c4e65681-aff7-411f-b6c8-5f7f9aa84faf
		summarizeBy: none
		sourceColumn: TotalSpaceKB

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column UsedSpaceKB
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c906b611-283c-442d-b5a9-fc9170bbf4f3
		summarizeBy: none
		sourceColumn: UsedSpaceKB

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column DataSpaceKB
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b684efcf-b659-456f-905d-3e607df953a6
		summarizeBy: none
		sourceColumn: DataSpaceKB

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column IndexKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0cdec451-1a41-4e68-9001-b025f05cb2de
		summarizeBy: none
		sourceColumn: IndexKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FileGroupKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5b88b196-b815-4778-a262-8eb01bbf9dee
		summarizeBy: none
		sourceColumn: FileGroupKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Allocation units' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Capacity")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Allocation units"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  renameColumns = Table.RenameColumns(
				    datasetToUse, 
				    {
				      {"AllocationUnitTypeDesc", "Allocation unit type"}, 
				      {"PartitionNumber", "Partition no."}
				    }
				  )
				in
				  renameColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

