table 'Blocked process'
	lineageTag: 99935d5e-e88b-456b-9f14-b780416e8255

	column 'Timestamp (UTC)'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: 9c3a678d-eb73-4b20-8b75-d72c966bd5f5
		summarizeBy: none
		sourceColumn: Timestamp (UTC)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 82d68628-8cf0-4473-8f3a-ff59b7de678d
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TimeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0375285c-f3e5-4c93-867e-6acc8278cb4e
		summarizeBy: none
		sourceColumn: TimeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data set'
		dataType: int64
		formatString: #,0
		lineageTag: b24a9090-0775-4bb1-9331-e54d3c026a66
		summarizeBy: none
		sourceColumn: Data set

		annotation SummarizationSetBy = User

	column BlocksAndDeadlocksKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4bf866b4-898e-457b-b318-c30cba76fc13
		summarizeBy: none
		sourceColumn: BlocksAndDeadlocksKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DatabaseKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d7bf3b7a-77cd-4358-a231-542ec9f19680
		summarizeBy: none
		sourceColumn: DatabaseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sort order'
		dataType: int64
		formatString: #,0
		lineageTag: 097e4e29-e148-457b-9356-a1662dfe84d7
		summarizeBy: none
		sourceColumn: Sort order

		annotation SummarizationSetBy = User

	column Type
		dataType: string
		lineageTag: fc1cac9d-8c69-45b6-ad22-5ace21cf46d4
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column SPID
		dataType: int64
		formatString: #,0
		lineageTag: c6922130-29f6-45b6-adf7-c31b45d6f9ce
		summarizeBy: none
		sourceColumn: SPID

		annotation SummarizationSetBy = User

	column Statement
		dataType: string
		lineageTag: fb60ddaf-a01e-4a1f-8aa3-f75e500f297e
		summarizeBy: none
		sourceColumn: Statement

		annotation SummarizationSetBy = Automatic

	partition 'Blocked process' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Blocks and deadlocks")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Blocked process"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  datasetSorted = Table.Sort(
				    datasetToUse,
				    {
				      { "EventTimestampUTC", Order.Ascending },
				      { "DataSet",           Order.Ascending },
				      { "Type",              Order.Ascending }
				    }
				  ),
				  addSortOrderColumn = Table.AddIndexColumn(
				    datasetSorted,
				    "LocalSortOrder",
				    1,
				    1,
				    Int64.Type
				  ),
				  selectColumns = Table.SelectColumns(
				    addSortOrderColumn,
				    {
				      "Type", 
				      "SPID", 
				      "Statement", 
				      "DataSet", 
				      "LocalSortOrder", 
				      "EventTimestampUTC", 
				      "Date", 
				      "TimeKey", 
				      "BlocksAndDeadlocksKey", 
				      "DatabaseKey"
				    }
				  ),
				  renameColumns = Table.RenameColumns(
				    selectColumns, 
				    {
				      {"DataSet", "Data set"}, 
				      {"LocalSortOrder", "Sort order"}, 
				      {"EventTimestampUTC", "Timestamp (UTC)"}
				    }
				  )
				in
				  renameColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

