table Configurations
	lineageTag: f7da455a-9dad-4f8c-b2eb-5c24aff47dd0

	column Key
		dataType: string
		lineageTag: 194004bb-5357-417f-b87a-4bd2eda65918
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 03f68a99-cf11-40da-852e-e9cc959090c7
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition Configurations = m
		mode: import
		queryGroup: Framework
		source = ```
				let
				  serverName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "ServerName")), 
				    "Value"
				  ), 
				  databaseName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "DatabaseName")), 
				    "Value"
				  ), 
				  schemaName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "SchemaName")), 
				    "Value"
				  ), 
				  dbList = Sql.Databases(serverName), 
				  db     = dbList{[Name = databaseName]}[Data], 
				  table  = db{[Schema = schemaName, Item = "Configurations"]}[Data]
				in
				  table
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

