table Connections
	lineageTag: c86da079-3b10-41e9-82ca-fbc2568a8f86

	column NumberOfConnections
		dataType: int64
		formatString: 0
		lineageTag: 7ca7d58d-a13b-4752-a2e8-9e115ed4962c
		summarizeBy: sum
		sourceColumn: NumberOfConnections

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: fcde8d0e-8d7a-4bd6-9016-8e4e42e1c7d2
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TimeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cb8c301e-656c-4aac-9018-07da3657c2b1
		summarizeBy: none
		sourceColumn: TimeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ConnectionInfoKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: da91b1c0-71f5-4059-af51-9984a6f1f7e4
		summarizeBy: none
		sourceColumn: ConnectionInfoKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Connections = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Connections")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Connections"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  selectColumns = Table.SelectColumns(
				    datasetToUse, 
				    {
				      "NumberOfConnections", 
				      "Date", 
				      "TimeKey", 
				      "ConnectionInfoKey"
				    }
				  )
				in
				  selectColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

