table 'Connection info'
	lineageTag: 14a7fe02-81d6-46aa-88c2-cde8f014870a

	column 'Auth. type'
		dataType: string
		lineageTag: 7755e90a-17b5-4096-b101-7c624df72310
		summarizeBy: none
		sourceColumn: Auth. type

		annotation SummarizationSetBy = Automatic

	column ConnectionInfoKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d38ada65-0f5e-474e-894e-f687df1e8768
		summarizeBy: none
		sourceColumn: ConnectionInfoKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Connection info' = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				  loadConfigFirstMatch = Table.First(
				    Table.SelectRows(
				      #"Data load", 
				      each List.Contains({"Connections"}, [Service]) and List.Contains({"Yes"}, [DataLoad])
				    )
				  ), 
				  loadConfig = 
				    if (loadConfigFirstMatch = null) then
				      "No"
				    else
				      Record.Field(loadConfigFirstMatch, "DataLoad"), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Connection info"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset,
				  renameColumns = Table.RenameColumns(
				    datasetToUse, 
				    {
				      {"AuthType", "Auth. type"}
				    }
				  )
				in
				  renameColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

