table 'Database state'
	lineageTag: 89b59759-8537-4d65-808b-3a6d2de0f59e

	column Collation
		dataType: string
		lineageTag: 0a3897e3-ed9f-4900-a82d-72872f369746
		summarizeBy: none
		sourceColumn: Collation

		annotation SummarizationSetBy = Automatic

	column 'Comp. level'
		dataType: int64
		formatString: 0
		lineageTag: 21e38c8d-bd01-42fe-bc4f-e0bcbdfa54bc
		summarizeBy: none
		sourceColumn: Comp. level

		annotation SummarizationSetBy = User

	column 'Delayed durability'
		dataType: string
		lineageTag: ccf1177a-31f2-4933-83d7-f7a0ecb43698
		summarizeBy: none
		sourceColumn: Delayed durability

		annotation SummarizationSetBy = Automatic

	column 'Page verify'
		dataType: string
		lineageTag: 1f39b7f7-1745-4193-937d-3924b4fc9c3e
		summarizeBy: none
		sourceColumn: Page verify

		annotation SummarizationSetBy = Automatic

	column 'Recovery model'
		dataType: string
		lineageTag: fd75ad94-eca4-44e4-8567-058750a69613
		summarizeBy: none
		sourceColumn: Recovery model

		annotation SummarizationSetBy = Automatic

	column 'Target recovery time in sec.'
		dataType: int64
		formatString: 0
		lineageTag: 072ccada-df10-4226-8347-f3094d6f1a53
		summarizeBy: none
		sourceColumn: Target recovery time in sec.

		annotation SummarizationSetBy = User

	column DatabaseKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bbd45d93-61de-40fb-b6a3-89b95edbfed3
		summarizeBy: none
		sourceColumn: DatabaseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Min. timestamp'
		dataType: dateTime
		formatString: dd-mmm-yyyy
		lineageTag: cb32825c-b1f1-434f-8723-447b0b783ce4
		summarizeBy: none
		sourceColumn: Min. timestamp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Max. timestamp'
		dataType: dateTime
		formatString: dd-mmm-yyyy
		lineageTag: 675f62a8-85f1-4da4-9ca5-f5852595ff61
		summarizeBy: none
		sourceColumn: Max. timestamp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column IsOnAlwaysOnPrimary
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 64ca9ec9-67cb-40a0-9291-0ac0accb9cb9
		summarizeBy: none
		sourceColumn: IsOnAlwaysOnPrimary

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Always On group'
		dataType: string
		lineageTag: d2878ec6-6079-4db0-a930-61e210d0aa68
		summarizeBy: none
		sourceColumn: Always On group

		annotation SummarizationSetBy = Automatic

	column 'Auto close'
		dataType: string
		lineageTag: 24c7db5f-bb6a-4f4f-834e-303e8c2dd266
		summarizeBy: none
		sourceColumn: Auto close

		annotation SummarizationSetBy = Automatic

	column 'Auto shrink'
		dataType: string
		lineageTag: 957aac7f-db84-49d9-ad48-b45aa821b078
		summarizeBy: none
		sourceColumn: Auto shrink

		annotation SummarizationSetBy = Automatic

	column 'Auto update stats. async.'
		dataType: string
		lineageTag: c9788893-8bb0-4822-9649-c8f7fc7a46b4
		summarizeBy: none
		sourceColumn: Auto update stats. async.

		annotation SummarizationSetBy = Automatic

	column Encrypted
		dataType: string
		lineageTag: cde211e9-4e46-488b-86d1-9e468700a084
		summarizeBy: none
		sourceColumn: Encrypted

		annotation SummarizationSetBy = Automatic

	column 'Mixed page allocation'
		dataType: string
		lineageTag: 8473a268-d5e6-458e-a8d8-c2f20a62340a
		summarizeBy: none
		sourceColumn: Mixed page allocation

		annotation SummarizationSetBy = Automatic

	column RCSI
		dataType: string
		lineageTag: 70746f61-d5f7-4e6b-b734-aff511b4eb0b
		summarizeBy: none
		sourceColumn: RCSI

		annotation SummarizationSetBy = Automatic

	column IsReadCommittedSnapshotOn
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d37bba29-e1fc-4bf2-889a-5fce0f92b468
		summarizeBy: none
		sourceColumn: IsReadCommittedSnapshotOn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsAutoCloseOn
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4d454fc4-6d47-409c-906a-e4033fe1797b
		summarizeBy: none
		sourceColumn: IsAutoCloseOn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsAutoShrinkOn
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d742dcb1-85a7-4261-a362-94630262e196
		summarizeBy: none
		sourceColumn: IsAutoShrinkOn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsAutoUpdateStatsAsyncOn
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 10c0ea84-e7e8-4222-8a8d-f327e0e0ff9c
		summarizeBy: none
		sourceColumn: IsAutoUpdateStatsAsyncOn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsEncrypted
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4d3d2d1a-60b7-4352-9f43-e414de054b5f
		summarizeBy: none
		sourceColumn: IsEncrypted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Param. forced'
		dataType: string
		lineageTag: 179fc0e0-4d6b-4bb2-b2ab-061717468d84
		summarizeBy: none
		sourceColumn: Param. forced

		annotation SummarizationSetBy = Automatic

	column IsInStandby
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 49340b2d-6669-4a90-894d-4050df75d4b6
		summarizeBy: none
		sourceColumn: IsInStandby

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Standby
		dataType: string
		lineageTag: f378bd57-e32a-4e9b-931f-36bde944f1e4
		summarizeBy: none
		sourceColumn: Standby

		annotation SummarizationSetBy = Automatic

	column IsReadOnly
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 27ae7085-265c-4f67-8ea9-fd4c417022de
		summarizeBy: none
		sourceColumn: IsReadOnly

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Read only'
		dataType: string
		lineageTag: 915d84f9-cbd7-495d-b4f2-769a3f3fd8a3
		summarizeBy: none
		sourceColumn: Read only

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: ac0badbf-e599-445a-896b-ffb7d3338755
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition 'Database state' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Database configuration")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Database state"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  selectColumns = Table.SelectColumns(
				    datasetToUse, 
				    {
				      "AlwaysOnGroupName", 
				      "CollationName", 
				      "CompatibilityLevel", 
				      "DelayedDurability", 
				      "IsAutoCloseOn", 
				      "IsAutoCloseOnTxt", 
				      "IsAutoShrinkOn", 
				      "IsAutoShrinkOnTxt", 
				      "IsAutoUpdateStatsAsyncOn", 
				      "IsAutoUpdateStatsAsyncOnTxt", 
				      "IsEncrypted", 
				      "IsEncryptedTxt", 
				      "IsInStandby", 
				      "IsInStandbyTxt", 
				      "IsMixedPageAllocationOnTxt", 
				      "IsOnAlwaysOnPrimary", 
				      "IsParameterizationForcedTxt", 
				      "IsReadCommittedSnapshotOn", 
				      "IsReadCommittedSnapshotOnTxt", 
				      "IsReadOnly", 
				      "IsReadOnlyTxt", 
				      "MaxTimestamp", 
				      "MinTimestamp", 
				      "PageVerifyOption", 
				      "RecoveryModel", 
				      "State", 
				      "TargetRecoveryTimeInSeconds", 
				      "DatabaseKey"
				    }
				  ), 
				  renameColumns = Table.RenameColumns(
				    selectColumns, 
				    {
				      {"AlwaysOnGroupName", "Always On group"}, 
				      {"CollationName", "Collation"}, 
				      {"CompatibilityLevel", "Comp. level"}, 
				      {"DelayedDurability", "Delayed durability"}, 
				      {"IsAutoCloseOnTxt", "Auto close"}, 
				      {"IsAutoShrinkOnTxt", "Auto shrink"}, 
				      {"IsAutoUpdateStatsAsyncOnTxt", "Auto update stats. async."}, 
				      {"IsEncryptedTxt", "Encrypted"}, 
				      {"IsInStandbyTxt", "Standby" }, 
				      {"IsMixedPageAllocationOnTxt", "Mixed page allocation"}, 
				      {"IsParameterizationForcedTxt", "Param. forced"}, 
				      {"IsReadCommittedSnapshotOnTxt", "RCSI"}, 
				      {"IsReadOnlyTxt", "Read only" }, 
				      {"MaxTimestamp", "Max. timestamp"}, 
				      {"MinTimestamp", "Min. timestamp"}, 
				      {"PageVerifyOption", "Page verify"}, 
				      {"RecoveryModel", "Recovery model"}, 
				      {"TargetRecoveryTimeInSeconds", "Target recovery time in sec."}
				    }
				  )
				in
				  renameColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

