table 'Data load'
	lineageTag: 098c2657-f3b4-4735-9543-4d102944117c

	column Service
		dataType: string
		lineageTag: ab36902a-920c-4bdf-b126-fd5c85efb11d
		summarizeBy: none
		sourceColumn: Service

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DataLoad
		dataType: string
		lineageTag: 2e7db343-a195-4175-92f1-2c9a0da73acb
		summarizeBy: none
		sourceColumn: DataLoad

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sevices affected'
		dataType: string
		lineageTag: 758fa606-4583-48a2-9c1b-048f5691b95b
		summarizeBy: none
		sourceColumn: Sevices affected

		annotation SummarizationSetBy = Automatic

	partition 'Data load' = m
		mode: import
		queryGroup: Framework
		source = ```
				let
				  systemServices = Table.FromRows(
				    Json.Document(
				      Binary.Decompress(
				        Binary.FromText(
				          "bVLbTsMwDP2VqM/7iQESTAJtwNAe1j14qZuZdU7lJIPy9aStmq5a3+LjyznH8X6fLQ2yV9/26JS2XJIJAp4sZ4ssOywm+RqltHIB1jhkH0CfQ52iyuqzU8CFKhCKLhpyj1CDJt/E+Ak8HMGhcvSHOW9APLWUWCjiAn/R5byFY9UX9N2WGXVbNA7cfA3PNHDWQcqu1gO0ammUjYa6SqhioscqhFI5H2HnSUchr9HEDTBp93RpBU6G1qfGke4m3qDBgcFEMpXZV0WKuNd5Bynb6ghpA2/kHLEZljbA6xeFIlYSsBn/7dbJIltWP9A4tWblBcqSdPyM2dqcP9DZIBF8tlcUtjK5ho6lAlYa9AmT2xE3gYpR4XtAaaZSOvyeZHYdn3eNWyFjcHS8A/Iz83cnqyjeZzyka6/v8A8=",
				          BinaryEncoding.Base64
				        ),
				        Compression.Deflate
				      )
				    ),
				    let
				      _t = ((type nullable text) meta [Serialized.Text = true])
				    in
				      type table [Service = _t, #"Sevices affected" = _t]
				  ), 
				  dataLoadUsed = 
				    if (#"Data load list" = null) then
				      let
				        addLoadEnabledColumn = Table.AddColumn(
				          systemServices, 
				          "DataLoad", 
				          each "Yes"
				        ), 
				        changedType = Table.TransformColumnTypes(
				          addLoadEnabledColumn, 
				          {
				            {"DataLoad", type text}
				          }
				        )
				      in
				        changedType
				    else
				      let
				        dataLoadList = Text.Split(#"Data load list", ","), 
				        dataLoadTable = Table.FromList(
				          dataLoadList, 
				          Splitter.SplitByNothing(), 
				          null, 
				          null, 
				          ExtraValues.Error
				        ), 
				        renamedColumns = Table.RenameColumns(
				          dataLoadTable, 
				          {
				            {"Column1", "DataLoadService"}
				          }
				        ), 
				        addLoadEnabledColumn = Table.AddColumn(
				          renamedColumns, 
				          "DataLoad", 
				          each "Yes"
				        ), 
				        changedType = Table.TransformColumnTypes(
				          addLoadEnabledColumn, 
				          {
				            {"DataLoadService", type text}, 
				            {"DataLoad", type text}
				          }
				        ), 
				        joinedTable = Table.FuzzyJoin(
				          systemServices, 
				          {"Service"}, 
				          changedType, 
				          {"DataLoadService"}, 
				          JoinKind.LeftOuter, 
				          [IgnoreCase = true, IgnoreSpace = false]
				        ), 
				        removedColumns = Table.RemoveColumns(joinedTable, "DataLoadService"), 
				        replacedValue = Table.ReplaceValue(
				          removedColumns, 
				          null, 
				          "No", 
				          Replacer.ReplaceValue, 
				          {"DataLoad"}
				        )
				      in
				        replacedValue, 
				  sortedRows = Table.Sort(
				    dataLoadUsed, 
				    {
				      {"Service", Order.Ascending}
				    }
				  )
				in
				  sortedRows
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

