table Deadlock
	lineageTag: a1c85509-9cec-4a28-91f8-bcff4b55284c

	column 'Timestamp (UTC)'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: 96f54c9b-ba21-4b82-922c-02a3b92b60d4
		summarizeBy: none
		sourceColumn: Timestamp (UTC)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: bd568a16-170d-485f-9230-09a87b335956
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TimeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 741c5641-4fbb-4947-953f-d19c4caa3ce8
		summarizeBy: none
		sourceColumn: TimeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data set'
		dataType: int64
		formatString: #,0
		lineageTag: 016f0550-421b-4ac2-a05a-99f5acc7bf34
		summarizeBy: none
		sourceColumn: Data set

		annotation SummarizationSetBy = User

	column BlocksAndDeadlocksKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 82f9650f-13cf-4f6a-8449-8df7d6799526
		summarizeBy: none
		sourceColumn: BlocksAndDeadlocksKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DatabaseKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 213187a2-b202-48d7-a5d9-647e0e80a8a1
		summarizeBy: none
		sourceColumn: DatabaseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SPID
		dataType: int64
		formatString: #,0
		lineageTag: 9969112d-9f70-4d6a-9ce3-4bfe871fd1a9
		summarizeBy: none
		sourceColumn: SPID

		annotation SummarizationSetBy = User

	column 'Inputbuf statement'
		dataType: string
		lineageTag: 2c289ede-c65d-4238-8163-a85391ba7b06
		summarizeBy: none
		sourceColumn: Inputbuf statement

		annotation SummarizationSetBy = Automatic

	column 'Frame statement'
		dataType: string
		lineageTag: 3b67fb75-8c0d-46f5-8dde-9510b2008839
		summarizeBy: none
		sourceColumn: Frame statement

		annotation SummarizationSetBy = Automatic

	column 'Sort order'
		dataType: int64
		formatString: #,0
		lineageTag: 794c57a7-a70b-42d2-b7b8-f928f0151788
		summarizeBy: none
		sourceColumn: Sort order

		annotation SummarizationSetBy = User

	partition Deadlock = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Blocks and deadlocks")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Deadlock"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  datasetSorted = Table.Sort(
				    datasetToUse,
				    {
				      { "EventTimestampUTC", Order.Ascending  },
				      { "DataSet",           Order.Ascending  },
				      { "SPID",              Order.Descending }
				    }
				  ),
				  addSortOrderColumn = Table.AddIndexColumn(
				    datasetSorted,
				    "LocalSortOrder",
				    1,
				    1,
				    Int64.Type
				  ),
				  selectColumns = Table.SelectColumns(
				    addSortOrderColumn,
				    {
				      "SPID", 
				      "InputbufStatement", 
				      "FrameStatement", 
				      "DataSet", 
				      "LocalSortOrder", 
				      "EventTimestampUTC", 
				      "Date", 
				      "TimeKey", 
				      "BlocksAndDeadlocksKey", 
				      "DatabaseKey"
				    }
				  ),
				  renameColumns = Table.RenameColumns(
				    selectColumns, 
				    {
				      {"InputbufStatement", "Inputbuf statement"}, 
				      {"FrameStatement", "Frame statement"}, 
				      {"DataSet", "Data set"}, 
				      {"LocalSortOrder", "Sort order"}, 
				      {"EventTimestampUTC", "Timestamp (UTC)"}
				    }
				  )
				in
				  renameColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

