table 'Error logs'
	lineageTag: a1138e61-46f6-43ec-9dc7-d4a613f5b28c

	column SetId
		dataType: int64
		formatString: #,0
		lineageTag: b9f9bc13-8af0-4689-b7cd-295cb8cbd30c
		summarizeBy: none
		sourceColumn: SetId

		annotation SummarizationSetBy = User

	column Id
		dataType: int64
		formatString: #,0
		lineageTag: 775de2f3-fb4b-4c53-8cb4-cd8caabd2779
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = User

	column Timestamp
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: c1344a5e-8428-41c4-8012-0cce36bd19d8
		summarizeBy: none
		sourceColumn: Timestamp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Process info.'
		dataType: string
		lineageTag: f820387c-30fe-45df-ae55-e2d7f4615940
		summarizeBy: none
		sourceColumn: Process info.

		annotation SummarizationSetBy = Automatic

	column Text
		dataType: string
		lineageTag: b0188bf6-5196-430e-bda0-b1b7c8f5b912
		summarizeBy: none
		sourceColumn: Text

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: int64
		formatString: 0
		lineageTag: a20dad7b-711a-439c-8a88-6b2ba44543bc
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = User

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3d0af3ca-2e40-44a4-b031-bb6ff2ae9f53
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Error logs' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Instance status")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Error logs"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  renamedColumns = Table.RenameColumns(
				    datasetToUse, 
				    {
				      {"LogDate", "Timestamp"}, 
				      {"ProcessInfo", "Process info."}
				    }
				  )
				in
				  renamedColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

