table 'Index partition'
	lineageTag: da37ce30-4b45-4dda-ae4e-98cf9a14e7c7

	column Database
		dataType: string
		lineageTag: 4817108b-5822-4d1a-8e3c-b73e0dd4b9d5
		summarizeBy: none
		sourceColumn: Database

		annotation SummarizationSetBy = Automatic

	column Schema
		dataType: string
		lineageTag: 55d893be-dee9-472c-a395-11da778641f0
		summarizeBy: none
		sourceColumn: Schema

		annotation SummarizationSetBy = Automatic

	column Object
		dataType: string
		lineageTag: 3128120e-8b1f-46ae-8556-36cf7044fe60
		summarizeBy: none
		sourceColumn: Object

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: string
		lineageTag: 8e95f031-3e49-415c-a1db-62695799b5b0
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Partition
		dataType: string
		lineageTag: 6e1795dd-aaa1-436b-91a1-c5c837f48e04
		summarizeBy: none
		sourceColumn: Partition

		annotation SummarizationSetBy = Automatic

	column IndexPartitionKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fc3be2ad-02fd-40f6-92c9-35ff89033c48
		summarizeBy: none
		sourceColumn: IndexPartitionKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Index partition' = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				  loadConfigFirstMatch = Table.First(
				    Table.SelectRows(
				      #"Data load", 
				      each List.Contains({"Statistics"}, [Service]) and List.Contains({"Yes"}, [DataLoad])
				    )
				  ), 
				  loadConfig = 
				    if (loadConfigFirstMatch = null) then
				      "No"
				    else
				      Record.Field(loadConfigFirstMatch, "DataLoad"), 
				  dbList = Sql.Databases(#"Server name"), 
				  db = dbList{[Name = #"Database name"]}[Data], 
				  table = db{[Schema = #"Schema name", Item = "Index partition"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset
				in
				  datasetToUse
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

