table 'Index configuration'
	lineageTag: 0afa5c34-57fa-4c90-b768-5dad6a411b69

	column 'Filter definition'
		dataType: string
		lineageTag: b4a58680-f3ea-47ee-8965-d2f3778ade03
		summarizeBy: none
		sourceColumn: Filter definition

		annotation SummarizationSetBy = Automatic

	column 'Index columns'
		dataType: string
		lineageTag: 31bffe7e-ff7c-48b6-824e-355e4db9d474
		summarizeBy: none
		sourceColumn: Index columns

		annotation SummarizationSetBy = Automatic

	column 'Included columns'
		dataType: string
		lineageTag: 35a52113-d0d6-41da-a2a1-086142add5be
		summarizeBy: none
		sourceColumn: Included columns

		annotation SummarizationSetBy = Automatic

	column ObjectKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e379ad75-a68f-41a5-928d-a064f0be140a
		summarizeBy: none
		sourceColumn: ObjectKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IndexKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c7f7f2c2-1864-4ea1-b18b-c02730eb23ea
		summarizeBy: none
		sourceColumn: IndexKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IndexTypeDesc
		dataType: string
		lineageTag: 51fd6377-020d-4a7d-a9c4-4de6c792d979
		summarizeBy: none
		sourceColumn: IndexTypeDesc

		annotation SummarizationSetBy = Automatic

	column 'Has filter'
		dataType: string
		lineageTag: 5cb5a69f-e993-4c19-ac18-faba4d6f0e0e
		summarizeBy: none
		sourceColumn: Has filter

		annotation SummarizationSetBy = Automatic

	column 'Is disabled'
		dataType: string
		lineageTag: 2a3a2824-9692-45e1-a0a0-5f36c0c69bb7
		summarizeBy: none
		sourceColumn: Is disabled

		annotation SummarizationSetBy = Automatic

	column 'Is hypothetical'
		dataType: string
		lineageTag: 0fd76442-e9c2-469c-8760-ce4dbd275438
		summarizeBy: none
		sourceColumn: Is hypothetical

		annotation SummarizationSetBy = Automatic

	column 'Is primary Key'
		dataType: string
		lineageTag: 8546c511-6c68-46e3-b860-acbb81484789
		summarizeBy: none
		sourceColumn: Is primary Key

		annotation SummarizationSetBy = Automatic

	column 'Is unique'
		dataType: string
		lineageTag: 3a6905da-16dd-483f-9054-cde64ddc592d
		summarizeBy: none
		sourceColumn: Is unique

		annotation SummarizationSetBy = Automatic

	column TableIsHeap
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fda18a2d-25e0-4cf2-8c2d-bae976dbd517
		summarizeBy: none
		sourceColumn: TableIsHeap

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Index configuration' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfigFirstMatch = Table.First(
				    Table.SelectRows(
				      #"Data load", 
				      each List.Contains(
				        {"Capacity", "Index usage"}, 
				        [Service]
				      )
				        and List.Contains({"Yes"}, [DataLoad])
				    )
				  ), 
				  loadConfig = 
				    if (loadConfigFirstMatch = null) then
				      "No"
				    else
				      Record.Field(loadConfigFirstMatch, "DataLoad"), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Index configuration"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  selectColumns = Table.SelectColumns(
				    datasetToUse,
				    {
				      "FilterDefinition", 
				      "HasFilterTxt", 
				      "IncludedColumns", 
				      "IndexColumns", 
				      "IndexTypeDesc", 
				      "IsDisabledTxt", 
				      "IsHypotheticalTxt", 
				      "IsPrimaryKeyTxt", 
				      "IsUniqueTxt", 
				      "TableIsHeap", 
				      "IndexKey", 
				      "ObjectKey"
				    }
				  ), 
				  renamedColumns = Table.RenameColumns(
				    selectColumns, 
				    {
				      {"FilterDefinition", "Filter definition"}, 
				      {"HasFilterTxt", "Has filter"}, 
				      {"IncludedColumns", "Included columns"}, 
				      {"IndexColumns", "Index columns"}, 
				      {"IsDisabledTxt", "Is disabled"}, 
				      {"IsHypotheticalTxt", "Is hypothetical"}, 
				      {"IsPrimaryKeyTxt", "Is primary Key"}, 
				      {"IsUniqueTxt", "Is unique"}
				    }
				  )
				in
				  renamedColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

