table 'Missing indexes - Index details'
	lineageTag: 1ab4a9dd-7a30-4e60-ac15-8c2e3f54279a

	column 'Equality columns'
		dataType: string
		lineageTag: 8b4c8dd7-3ec3-474b-b22a-39ba8862f6c2
		summarizeBy: none
		sourceColumn: Equality columns

		annotation SummarizationSetBy = Automatic

	column 'Inequality columns'
		dataType: string
		lineageTag: 45caf1ec-e11a-4ed1-8ddb-c2ec34b64dc5
		summarizeBy: none
		sourceColumn: Inequality columns

		annotation SummarizationSetBy = Automatic

	column 'Included columns'
		dataType: string
		lineageTag: 3a4ce054-3cdd-4778-9051-e90798575892
		summarizeBy: none
		sourceColumn: Included columns

		annotation SummarizationSetBy = Automatic

	column LastUserSeek
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 150efdf4-6340-4a0d-9f06-de979fb945e2
		summarizeBy: none
		sourceColumn: LastUserSeek

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AvgTotalUserCost
		dataType: double
		isHidden
		lineageTag: bca1079f-7f1b-49d8-8f74-93becc37c085
		summarizeBy: none
		sourceColumn: AvgTotalUserCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AvgUserImpact
		dataType: double
		isHidden
		lineageTag: 30ef4155-84c0-46a5-92fe-88f50cffe381
		summarizeBy: none
		sourceColumn: AvgUserImpact

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ObjectKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 30e255e1-0af8-49b0-a353-80065848f061
		summarizeBy: none
		sourceColumn: ObjectKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column MissingIndexStatementKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a8a4ec85-0eca-4037-a040-ce3489aee9ed
		summarizeBy: none
		sourceColumn: MissingIndexStatementKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserSeeks
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4930b055-18f4-498c-bc6e-4d55ac5054be
		summarizeBy: none
		sourceColumn: UserSeeks

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition 'Missing indexes - Index details' = m
		mode: import
		queryGroup: Facts
		source =
				let
				  Source = #"Missing indexes",
				  SelectColumns = Table.SelectColumns(
				    Source,
				    {
				      "Equality columns",
				      "Inequality columns",
				      "Included columns",
				      "UserSeeks",
				      "LastUserSeek",
				      "AvgTotalUserCost",
				      "AvgUserImpact",
				      "ObjectKey",
				      "MissingIndexStatementKey"
				    }
				  )
				in
				    SelectColumns

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

