table 'Resource governor resource pools'
	lineageTag: d6453e72-11dc-45c6-a987-88961d8af30e

	column PoolName
		dataType: string
		lineageTag: feed7dbe-94b4-4c7d-aa3d-2030cc9b5c50
		summarizeBy: none
		sourceColumn: PoolName

		annotation SummarizationSetBy = Automatic

	column MinCPUpercent
		dataType: string
		lineageTag: 08591a13-0fef-4f51-8403-7f32b4344de3
		summarizeBy: none
		sourceColumn: MinCPUpercent

		annotation SummarizationSetBy = Automatic

	column MaxCPUpercent
		dataType: string
		lineageTag: 6a01fb7a-6788-4600-a833-7a534b970c2d
		summarizeBy: none
		sourceColumn: MaxCPUpercent

		annotation SummarizationSetBy = Automatic

	column MinMemoryPercent
		dataType: string
		lineageTag: f1440126-90e0-4a4e-903d-9a6d9beb8af9
		summarizeBy: none
		sourceColumn: MinMemoryPercent

		annotation SummarizationSetBy = Automatic

	column MaxMemoryPercent
		dataType: string
		lineageTag: d905da75-558d-4174-b8e1-4884d3ebae32
		summarizeBy: none
		sourceColumn: MaxMemoryPercent

		annotation SummarizationSetBy = Automatic

	column CapCPUpercent
		dataType: string
		lineageTag: 598007b3-82ad-4f05-bb5f-7be58b80614f
		summarizeBy: none
		sourceColumn: CapCPUpercent

		annotation SummarizationSetBy = Automatic

	column MinIOPSperVolume
		dataType: string
		lineageTag: 1dfcc463-6dd1-4799-84c6-760bc96054be
		summarizeBy: none
		sourceColumn: MinIOPSperVolume

		annotation SummarizationSetBy = Automatic

	column MaxIOPSperVolume
		dataType: string
		lineageTag: f404caad-54cd-45d9-a6e8-951e786ea447
		summarizeBy: none
		sourceColumn: MaxIOPSperVolume

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: 9b4ac3c3-729b-49c5-b976-d0c81bc5db5d
		summarizeBy: none
		sourceColumn: Timestamp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	partition 'Resource governor resource pools' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Resource Governor configuration")), 
				    "DataLoad"
				  ), 
				  serverName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "ServerName")), 
				    "Value"
				  ), 
				  databaseName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "DatabaseName")), 
				    "Value"
				  ), 
				  schemaName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "SchemaName")), 
				    "Value"
				  ), 
				  dbList = Sql.Databases(serverName), 
				  db     = dbList{[Name = databaseName]}[Data], 
				  table  = db{[Schema = schemaName, Item = "Resource governor resource pools"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset
				in
				  datasetToUse
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

