table 'Resource governor external resource pools'
	lineageTag: 82a0d71b-c29e-494c-ab1b-1ea2af028da3

	column PoolName
		dataType: string
		lineageTag: 933627bd-0a71-436b-948c-79466aaf0e1f
		summarizeBy: none
		sourceColumn: PoolName

		annotation SummarizationSetBy = Automatic

	column MaxCPUpercent
		dataType: string
		lineageTag: 482fcb6b-fba2-4470-8804-a85326ca037b
		summarizeBy: none
		sourceColumn: MaxCPUpercent

		annotation SummarizationSetBy = Automatic

	column MaxMemoryPercent
		dataType: string
		lineageTag: a126b37e-9d84-4ff7-b04e-5ea5c1bc050d
		summarizeBy: none
		sourceColumn: MaxMemoryPercent

		annotation SummarizationSetBy = Automatic

	column MaxProcesses
		dataType: string
		lineageTag: 9eed02dd-7d61-476c-af8b-538feca717df
		summarizeBy: none
		sourceColumn: MaxProcesses

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 03547c94-bd9d-48a8-b71a-97d79fe47ad0
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: eab32237-04b8-44d7-9428-bab85f94d4e5
		summarizeBy: none
		sourceColumn: Timestamp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	partition 'Resource governor external resource pools' = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Resource Governor configuration")), 
				    "DataLoad"
				  ), 
				  serverName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "ServerName")), 
				    "Value"
				  ), 
				  databaseName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "DatabaseName")), 
				    "Value"
				  ), 
				  schemaName = Record.Field(
				    Table.First(Table.SelectRows(#"Connection parameters", each [Key] = "SchemaName")), 
				    "Value"
				  ), 
				  dbList = Sql.Databases(serverName), 
				  db     = dbList{[Name = databaseName]}[Data], 
				  table  = db{[Schema = schemaName, Item = "Resource governor external resource pools"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset
				in
				  datasetToUse
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

