table Retentions
	lineageTag: 43f18a8f-7646-427a-bc78-f6cd3a13d618

	column Table
		dataType: string
		lineageTag: 11a3beb7-1daf-4faa-be6d-885a494a35b8
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Days
		dataType: int64
		formatString: 0
		lineageTag: e3880d60-6f76-43cc-a7e8-c5b2b6ab80be
		summarizeBy: none
		sourceColumn: Days

		annotation SummarizationSetBy = User

	column Enabled
		dataType: string
		lineageTag: c7f69771-1e15-4fe1-9a0d-cf8c84fb9877
		summarizeBy: none
		sourceColumn: Enabled

		annotation SummarizationSetBy = Automatic

	column 'Last executed UTC'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: 5b193872-d00b-4a67-9fb0-8e168a7317b2
		summarizeBy: none
		sourceColumn: Last executed UTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Last started UTC'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: 4ad7b35a-526f-4c0f-bd7f-0886b7e5b0b6
		summarizeBy: none
		sourceColumn: Last started UTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Filter
		dataType: string
		lineageTag: b641d9f0-9457-459d-9986-fb23e4b69ce4
		summarizeBy: none
		sourceColumn: Filter

		annotation SummarizationSetBy = Automatic

	partition Retentions = m
		mode: import
		queryGroup: Framework
		source = ```
				let
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Retentions"]}[Data],
				  selectColumns = Table.SelectColumns(
				    table,
				    {
				      "Days", 
				      "EnabledTxt", 
				      "Filter", 
				      "LastExecutedUTC", 
				      "LastStartedUTC", 
				      "Table"
				    }
				  ), 
				  renamedColumns = Table.RenameColumns(
				    selectColumns, 
				    {
				      {"EnabledTxt", "Enabled"}, 
				      {"LastExecutedUTC", "Last executed UTC"}, 
				      {"LastStartedUTC", "Last started UTC"}
				    }
				  )
				in
				  renamedColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

