table Schedules
	lineageTag: 2de1f86e-599c-4505-9f28-a284fcc8a1ae

	column Enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6229c590-9c40-4c9e-ae91-555f2050e61b
		summarizeBy: none
		sourceColumn: Enabled

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 88603033-e792-4788-b5a0-2ac236bb00aa
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Task
		dataType: string
		lineageTag: 56bbffe8-c394-433f-9da1-a71096dba90d
		summarizeBy: none
		sourceColumn: Task

		annotation SummarizationSetBy = Automatic

	column Parameters
		dataType: string
		lineageTag: e4c0f8a6-b61b-4a2e-b6bc-2c7fa9f5f300
		summarizeBy: none
		sourceColumn: Parameters

		annotation SummarizationSetBy = Automatic

	column 'Execution delay in sec.'
		dataType: int64
		formatString: 0
		lineageTag: 7ab4110a-db3d-4d9f-acc9-412a2031ee30
		summarizeBy: none
		sourceColumn: Execution delay in sec.

		annotation SummarizationSetBy = User

	column 'From time'
		dataType: dateTime
		formatString: hh:nn:ss
		lineageTag: 60684e16-f823-43a0-8fdf-894a0d1ab081
		summarizeBy: none
		sourceColumn: From time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isCustom":true}

	column 'To time'
		dataType: dateTime
		formatString: hh:nn:ss
		lineageTag: d3d07880-5ca5-4a05-9f86-15a3b70379e8
		summarizeBy: none
		sourceColumn: To time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isCustom":true}

	column Monday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 127464f6-8e02-46a9-b13b-11863100a4af
		summarizeBy: none
		sourceColumn: Monday

		annotation SummarizationSetBy = Automatic

	column Tuesday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1b42a8a8-7403-4324-a3ab-1e735038de30
		summarizeBy: none
		sourceColumn: Tuesday

		annotation SummarizationSetBy = Automatic

	column Wednesday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0aafe7da-571c-43eb-ab29-3ba0b443ee1e
		summarizeBy: none
		sourceColumn: Wednesday

		annotation SummarizationSetBy = Automatic

	column Thursday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b12da94d-94d2-49ba-909d-d9b567e8aed0
		summarizeBy: none
		sourceColumn: Thursday

		annotation SummarizationSetBy = Automatic

	column Friday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 679bcb2c-c93b-4395-99ee-4d5bafe2e2e7
		summarizeBy: none
		sourceColumn: Friday

		annotation SummarizationSetBy = Automatic

	column Saturday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7c9433af-b21f-4f74-8cc0-a297f36d714b
		summarizeBy: none
		sourceColumn: Saturday

		annotation SummarizationSetBy = Automatic

	column Sunday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9f2c6e25-2f63-4d13-aee7-f10d290bea82
		summarizeBy: none
		sourceColumn: Sunday

		annotation SummarizationSetBy = Automatic

	column 'Last started UTC'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: dea16020-ed97-44e7-8c72-ae32c3cb4b33
		summarizeBy: none
		sourceColumn: Last started UTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Last executed UTC'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: d3d79f31-f255-4072-a3b4-7e81ffb78bf6
		summarizeBy: none
		sourceColumn: Last executed UTC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Last error message'
		dataType: string
		lineageTag: c63f8cea-9d89-4b5e-846d-e4fdc0ef245f
		summarizeBy: none
		sourceColumn: Last error message

		annotation SummarizationSetBy = Automatic

	partition Schedules = m
		mode: import
		queryGroup: Framework
		source = ```
				let
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Schedules"]}[Data], 
				  renameColumns = Table.RenameColumns(
				    table, 
				    {
				      {"LastErrorMessage", "Last error message"}
				    }
				  )
				in
				  renameColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

