table Triggers
	lineageTag: 1033cd32-8333-48e1-b78c-2d1682e4cc23

	column 'Parent class'
		dataType: string
		lineageTag: d4ddb83d-0485-49e7-91f4-5ee0e983e695
		summarizeBy: none
		sourceColumn: Parent class

		annotation SummarizationSetBy = Automatic

	column 'Parent object'
		dataType: string
		lineageTag: 2c40d87f-f27d-4886-8e78-c16a880cddb6
		summarizeBy: none
		sourceColumn: Parent object

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 76c92df6-e673-4d27-b3d4-8df36badc023
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Created date'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: 14860fb7-7b7f-44d3-8305-6ecb38238cfb
		summarizeBy: none
		sourceColumn: Created date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Modified date'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss
		lineageTag: 7a191f0b-6d99-4728-b119-5c242d81ba41
		summarizeBy: none
		sourceColumn: Modified date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Trigger type'
		dataType: string
		lineageTag: a95feeb7-9062-4025-8639-c88227eeca44
		summarizeBy: none
		sourceColumn: Trigger type

		annotation SummarizationSetBy = Automatic

	column DatabaseKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d1859d19-aeab-4893-bae6-cadc88418a94
		summarizeBy: none
		sourceColumn: DatabaseKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Trigger name'
		dataType: string
		lineageTag: 819037f0-c8d6-4dd2-9719-dca3725e77c5
		summarizeBy: none
		sourceColumn: Trigger name

		annotation SummarizationSetBy = Automatic

	column 'Is disabled'
		dataType: string
		lineageTag: ad451ec7-abba-4e89-b389-94c428d44edb
		summarizeBy: none
		sourceColumn: Is disabled

		annotation SummarizationSetBy = Automatic

	column 'Is MS shipped'
		dataType: string
		lineageTag: de375ee6-3e44-4110-95fd-3138e7d0be28
		summarizeBy: none
		sourceColumn: Is MS shipped

		annotation SummarizationSetBy = Automatic

	column 'Is not for replication'
		dataType: string
		lineageTag: f7301a56-6b84-426e-bc0b-c62b81edf3c5
		summarizeBy: none
		sourceColumn: Is not for replication

		annotation SummarizationSetBy = Automatic

	column IsDisabled
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d93e0b61-c4ef-480f-8974-1dbd17179f2a
		summarizeBy: none
		sourceColumn: IsDisabled

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsMSShipped
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 85d2ca0f-b3e9-4ab4-8ed0-67c8feede585
		summarizeBy: none
		sourceColumn: IsMSShipped

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsNotForReplication
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4f039bea-5134-4965-bf8f-e4f5cec64eb6
		summarizeBy: none
		sourceColumn: IsNotForReplication

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Triggers = m
		mode: import
		queryGroup: Facts
		source = ```
				let
				  loadConfig = Record.Field(
				    Table.First(Table.SelectRows(#"Data load", each [Service] = "Triggers")), 
				    "DataLoad"
				  ), 
				  dbList = Sql.Databases(#"Server name"), 
				  db     = dbList{[Name = #"Database name"]}[Data], 
				  table  = db{[Schema = #"Schema name", Item = "Triggers"]}[Data], 
				  emptyDataset = Table.FirstN(table, 0), 
				  datasetToUse = if (loadConfig = "Yes") then table else emptyDataset, 
				  selectColumns = Table.SelectColumns(
				    datasetToUse, 
				    {
				      "CreateDate", 
				      "IsDisabled", 
				      "IsDisabledTxt", 
				      "IsMSShipped", 
				      "IsMSShippedTxt", 
				      "IsNotForReplication", 
				      "IsNotForReplicationTxt", 
				      "ModifyDate", 
				      "ParentClass", 
				      "ParentObject", 
				      "TriggerName", 
				      "TriggerType", 
				      "Type", 
				      "DatabaseKey"
				    }
				  ), 
				  renameColumns = Table.RenameColumns(
				    selectColumns, 
				    {
				      {"CreateDate", "Created date"}, 
				      {"IsDisabledTxt", "Is disabled"}, 
				      {"IsMSShippedTxt", "Is MS shipped"}, 
				      {"IsNotForReplicationTxt", "Is not for replication"}, 
				      {"ModifyDate", "Modified date"}, 
				      {"ParentClass", "Parent class"}, 
				      {"ParentObject", "Parent object"}, 
				      {"TriggerName", "Trigger name"}, 
				      {"TriggerType", "Trigger type"}
				    }
				  )
				in
				  renameColumns
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

