$outputFile = "..\build\FHSQLMonitor.sql"

$versionNumber = "v2.13.0"

$buildTimeStr = (Get-Date).ToString("yyyy:MM:dd HH:mm:ss")

if (Test-Path $outputFile) {
    Clear-Content $outputFile
}

Add-Content $outputFile "USE master;"
Add-Content $outputFile ""
Add-Content $outputFile "SET NOCOUNT ON;"
Add-Content $outputFile ""
Add-Content $outputFile "--"
Add-Content $outputFile ("-- FHSQLMonitor " + $versionNumber + " - " + $buildTimeStr)
Add-Content $outputFile "--"
Add-Content $outputFile ""
Add-Content $outputFile "BEGIN"
Add-Content $outputFile "	--"
Add-Content $outputFile "	-- Installation parameters - They are used both during a fresh installation and during an update"
Add-Content $outputFile "	--"
Add-Content $outputFile "	DECLARE @fhSQLMonitorDatabase           nvarchar(128) = 'FHSQLMonitor';"
Add-Content $outputFile "	DECLARE @pbiSchema                      nvarchar(128) = 'FHSM';"
Add-Content $outputFile "	DECLARE @olaDatabase                    nvarchar(128) = NULL;"
Add-Content $outputFile ""
Add-Content $outputFile "	--"
Add-Content $outputFile "	-- Service parameters - They are only used during a fresh installation and not during an update"
Add-Content $outputFile "	--   When updating the already configured values in the tables dbo.fhsmSchedules and dbo.fhsmRetentions remains unchanged"
Add-Content $outputFile "	--"
Add-Content $outputFile "	DECLARE @createSQLAgentJobs             bit           = 1;"
Add-Content $outputFile "	DECLARE @blocksAndDeadlocksFilePath     nvarchar(260) = NULL;"
Add-Content $outputFile "	DECLARE @fhsqlAgentJobNameType0         nvarchar(128) = 'FHSQLMonitor type 0 in ' + @fhSQLMonitorDatabase;"
Add-Content $outputFile "	DECLARE @fhsqlAgentJobNameType1         nvarchar(128) = 'FHSQLMonitor type 1 in ' + @fhSQLMonitorDatabase;"
Add-Content $outputFile ""
Add-Content $outputFile "	DECLARE @enableAgentJobs                bit = 1;"
Add-Content $outputFile "	DECLARE @enableAgentJobsPerformance     bit = 1;"
Add-Content $outputFile "	DECLARE @enableAgeOfStatistics          bit = 1;"
Add-Content $outputFile "	DECLARE @enableBackupStatus             bit = 1;"
Add-Content $outputFile "	DECLARE @enableBlocksAndDeadlocks       bit = 1;"
Add-Content $outputFile "	DECLARE @enableCapacity                 bit = 1;"
Add-Content $outputFile "	DECLARE @enableConnections              bit = 1;"
Add-Content $outputFile "	DECLARE @enableCPUUtilization           bit = 1;"
Add-Content $outputFile "	DECLARE @enableDatabaseIO               bit = 1;"
Add-Content $outputFile "	DECLARE @enableDatabaseState            bit = 1;"
Add-Content $outputFile "	DECLARE @enableIndexOperational         bit = 1;"
Add-Content $outputFile "	DECLARE @enableIndexPhysical            bit = 1;"
Add-Content $outputFile "	DECLARE @enableIndexUsage               bit = 1;"
Add-Content $outputFile "	DECLARE @enableInstanceState            bit = 1;"
Add-Content $outputFile "	DECLARE @enableMemory                   bit = 1;"
Add-Content $outputFile "	DECLARE @enableMissingIndexes           bit = 1;"
Add-Content $outputFile "	DECLARE @enablePerformanceStatistics    bit = 1;"
Add-Content $outputFile "	DECLARE @enablePlanCacheUsage           bit = 1;"
Add-Content $outputFile "	DECLARE @enablePlanGuides               bit = 1;"
Add-Content $outputFile "	DECLARE @enableQueryStatistics          bit = 1;"
Add-Content $outputFile "	DECLARE @enableTriggers                 bit = 1;"
Add-Content $outputFile "	DECLARE @enableWaitStatistics           bit = 1;"
Add-Content $outputFile "	DECLARE @enableWhoIsActive              bit = 1;"
Add-Content $outputFile ""
Add-Content $outputFile "	DECLARE @enableLogShipping              bit = 0;"
Add-Content $outputFile "	DECLARE @enableIndexRebuild             bit = 0;"
Add-Content $outputFile "	DECLARE @enableIndexReorganize          bit = 0;"
Add-Content $outputFile "	DECLARE @enableUpdateAllStatistics      bit = 0;"
Add-Content $outputFile "	DECLARE @enableUpdateModifiedStatistics bit = 0;"
Add-Content $outputFile "END;"
Add-Content $outputFile ""
Add-Content $outputFile "--"
Add-Content $outputFile "-- No need to change more from here on"
Add-Content $outputFile "--"
Add-Content $outputFile ""
Add-Content $outputFile "DECLARE @currentAgentJobName nvarchar(128);"
Add-Content $outputFile "DECLARE @currentVersion nvarchar(128);"
Add-Content $outputFile "DECLARE @installationJobExecuting nvarchar(16);"
Add-Content $outputFile "DECLARE @installationJobStatus int;"
Add-Content $outputFile "DECLARE @installationMsg nvarchar(max);"
Add-Content $outputFile "DECLARE @installationNow datetime;"
Add-Content $outputFile "DECLARE @installationNowStr nvarchar(max);"
Add-Content $outputFile "DECLARE @installationWaitCnt int;"
Add-Content $outputFile "DECLARE @installUpgradeFlag int;"
Add-Content $outputFile "DECLARE @jobDisabledFlag bit;"
Add-Content $outputFile "DECLARE @jobName nvarchar(128);"
Add-Content $outputFile "DECLARE @jobStatus int;"
Add-Content $outputFile "DECLARE @jobs TABLE(JobName nvarchar(128), JobStatus int);"
Add-Content $outputFile "DECLARE @serverInfo nvarchar(max);"
Add-Content $outputFile "DECLARE @stmt nvarchar(max);"
Add-Content $outputFile ""
Add-Content $outputFile "IF (DB_ID(@fhSQLMonitorDatabase) IS NULL)"
Add-Content $outputFile "BEGIN"
Add-Content $outputFile "	SET @installUpgradeFlag = 1;	-- 1: Install"
Add-Content $outputFile "END"
Add-Content $outputFile "ELSE BEGIN"
Add-Content $outputFile "	SET @installUpgradeFlag = 2;	-- 2: Upgrade"
Add-Content $outputFile ""
Add-Content $outputFile "	SET @stmt = 'SET @currentVersion = ' + QUOTENAME(@fhSQLMonitorDatabase) + '.dbo.fhsmFNGetConfiguration(''Version'');';"
Add-Content $outputFile "	EXEC sp_executesql @stmt, N'@currentVersion nvarchar(128) OUTPUT', @currentVersion = @currentVersion OUTPUT;"
Add-Content $outputFile "	SET @currentVersion = COALESCE('v' + @currentVersion, 'N.A.');"
Add-Content $outputFile "	SET @stmt = '"
Add-Content $outputFile "		USE ' + QUOTENAME(@fhSQLMonitorDatabase) + ';"
Add-Content $outputFile ""
Add-Content $outputFile "		IF NOT EXISTS(SELECT * FROM dbo.fhsmConfigurations AS c WHERE (c.[Key] LIKE ''AgentJobName%''))"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			INSERT INTO dbo.fhsmConfigurations([Key], Value)"
Add-Content $outputFile "			VALUES(''AgentJobName'', ''FHSQLMonitor in FHSQLMonitor'');"
Add-Content $outputFile "		END;"
Add-Content $outputFile "	';"
Add-Content $outputFile "	EXEC(@stmt);"
Add-Content $outputFile "	SET @stmt = '"
Add-Content $outputFile "		USE ' + QUOTENAME(@fhSQLMonitorDatabase) + ';"
Add-Content $outputFile ""
Add-Content $outputFile "		SELECT c.Value"
Add-Content $outputFile "		FROM dbo.fhsmConfigurations AS c"
Add-Content $outputFile "		WHERE (c.[Key] = ''AgentJobName'') OR (c.[Key] LIKE ''AgentJobName[01]'')"
Add-Content $outputFile "		ORDER BY c.[Key];"
Add-Content $outputFile "	';"
Add-Content $outputFile "	INSERT INTO @jobs(JobName)"
Add-Content $outputFile "	EXEC(@stmt);"
Add-Content $outputFile "END;"
Add-Content $outputFile ""
Add-Content $outputFile "SET @serverInfo = @@SERVERNAME;"
Add-Content $outputFile ""
Add-Content $outputFile "RAISERROR('', 0, 1) WITH NOWAIT;"
Add-Content $outputFile ("SET @installationMsg = CASE @installUpgradeFlag WHEN 1 THEN 'Install version " + $versionNumber + "' + ' of' ELSE 'Upgrade' END + ' FHSQLMonitor in database ' + @fhSQLMonitorDatabase + ' on ' + @serverInfo + ' ' + CASE @installUpgradeFlag WHEN 1 THEN '' ELSE 'from ' + @currentVersion + ' to " + $versionNumber + "' END;")
Add-Content $outputFile "RAISERROR(@installationMsg, 0, 1) WITH NOWAIT;"
Add-Content $outputFile ""
Add-Content $outputFile "--"
Add-Content $outputFile "-- Get job enabled status and disable if executing"
Add-Content $outputFile "--"
Add-Content $outputFile "BEGIN"
Add-Content $outputFile "	SET @jobDisabledFlag = 0;"
Add-Content $outputFile ""
Add-Content $outputFile "	DECLARE jCur CURSOR LOCAL READ_ONLY FAST_FORWARD FOR"
Add-Content $outputFile "	SELECT j.JobName"
Add-Content $outputFile "	FROM @jobs AS j"
Add-Content $outputFile "	ORDER BY j.JobName;"
Add-Content $outputFile ""
Add-Content $outputFile "	OPEN jCur;"
Add-Content $outputFile ""
Add-Content $outputFile "	WHILE (1 = 1)"
Add-Content $outputFile "	BEGIN"
Add-Content $outputFile "		FETCH NEXT FROM jCur"
Add-Content $outputFile "		INTO @jobName;"
Add-Content $outputFile ""
Add-Content $outputFile "		IF (@@FETCH_STATUS <> 0)"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			BREAK;"
Add-Content $outputFile "		END;"
Add-Content $outputFile ""
Add-Content $outputFile "		SET @installationJobStatus ="
Add-Content $outputFile "			COALESCE("
Add-Content $outputFile "				("
Add-Content $outputFile "					SELECT sj.enabled"
Add-Content $outputFile "					FROM msdb.dbo.sysjobs AS sj"
Add-Content $outputFile "					WHERE (sj.name = @jobName)"
Add-Content $outputFile "				),"
Add-Content $outputFile "				-1"
Add-Content $outputFile "			);"
Add-Content $outputFile ""
Add-Content $outputFile "		UPDATE j"
Add-Content $outputFile "		SET j.JobStatus = @installationJobStatus"
Add-Content $outputFile "		FROM @jobs AS j"
Add-Content $outputFile "		WHERE (j.JobName = @jobName);"
Add-Content $outputFile ""
Add-Content $outputFile "		IF (@installationJobStatus IN (0, 1))"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			RAISERROR('', 0, 1) WITH NOWAIT;"
Add-Content $outputFile "			SET @installationMsg = 'Agent job ' + QUOTENAME(@jobName) + ' is ' + CASE @installationJobStatus WHEN 1 THEN 'enabled' WHEN 0 THEN 'disabled' END;"
Add-Content $outputFile "			RAISERROR(@installationMsg, 0, 1) WITH NOWAIT;"
Add-Content $outputFile "		END;"
Add-Content $outputFile ""
Add-Content $outputFile "		--"
Add-Content $outputFile "		-- Disable job if enabled"
Add-Content $outputFile "		--"
Add-Content $outputFile "		IF (@installationJobStatus = 1)"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			SET @jobDisabledFlag = 1;"
Add-Content $outputFile ""
Add-Content $outputFile "			SET @installationMsg = 'Disabling job ' + QUOTENAME(@jobName);"
Add-Content $outputFile "			RAISERROR(@installationMsg, 0, 1) WITH NOWAIT;"
Add-Content $outputFile ""
Add-Content $outputFile "			EXEC msdb.dbo.sp_update_job"
Add-Content $outputFile "				@job_name = @jobName,"
Add-Content $outputFile "				@enabled = 0;"
Add-Content $outputFile "		END;"
Add-Content $outputFile "	END;"
Add-Content $outputFile ""
Add-Content $outputFile "	CLOSE jCur;"
Add-Content $outputFile "	DEALLOCATE jCur;"
Add-Content $outputFile ""
Add-Content $outputFile "	IF (@jobDisabledFlag = 1)"
Add-Content $outputFile "	BEGIN"
Add-Content $outputFile "		WAITFOR DELAY '00:00:10';"
Add-Content $outputFile "	END;"
Add-Content $outputFile "END;"
Add-Content $outputFile ""
Add-Content $outputFile "--"
Add-Content $outputFile "-- Wait until jobs has stopped executing"
Add-Content $outputFile "--"
Add-Content $outputFile "BEGIN"
Add-Content $outputFile "	DECLARE jCur CURSOR LOCAL READ_ONLY FAST_FORWARD FOR"
Add-Content $outputFile "	SELECT j.JobName"
Add-Content $outputFile "	FROM @jobs AS j"
Add-Content $outputFile "	ORDER BY j.JobName;"
Add-Content $outputFile ""
Add-Content $outputFile "	OPEN jCur;"
Add-Content $outputFile ""
Add-Content $outputFile "	WHILE (1 = 1)"
Add-Content $outputFile "	BEGIN"
Add-Content $outputFile "		FETCH NEXT FROM jCur"
Add-Content $outputFile "		INTO @jobName;"
Add-Content $outputFile ""
Add-Content $outputFile "		IF (@@FETCH_STATUS <> 0)"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			BREAK;"
Add-Content $outputFile "		END;"
Add-Content $outputFile ""
Add-Content $outputFile "		SET @installationWaitCnt = 0;"
Add-Content $outputFile ""
Add-Content $outputFile "		SET @installationJobExecuting = 'Running';"
Add-Content $outputFile ""
Add-Content $outputFile "		WHILE (@installationJobExecuting = 'Running')"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			SET @installationJobExecuting = ("
Add-Content $outputFile "				SELECT"
Add-Content $outputFile "					TOP 1"
Add-Content $outputFile "					CASE"
Add-Content $outputFile "						WHEN ja.job_id IS NOT NULL AND ja.stop_execution_date IS NULL THEN 'Running'"
Add-Content $outputFile "						WHEN jh.run_status = 0 THEN 'Failed'"
Add-Content $outputFile "						WHEN jh.run_status = 1 THEN 'Succeeded'"
Add-Content $outputFile "						WHEN jh.run_status = 2 THEN 'Retry'"
Add-Content $outputFile "						WHEN jh.run_status = 3 THEN 'Cancelled'"
Add-Content $outputFile "					END AS JobLastOutcome"
Add-Content $outputFile "				FROM msdb.dbo.sysjobs AS j"
Add-Content $outputFile "				LEFT JOIN msdb.dbo.sysjobactivity AS ja ON"
Add-Content $outputFile "					(ja.job_id = j.job_id)"
Add-Content $outputFile "					AND (ja.run_requested_date IS NOT NULL)"
Add-Content $outputFile "					AND (ja.start_execution_date IS NOT NULL)"
Add-Content $outputFile "				LEFT JOIN msdb.dbo.sysjobsteps AS js ON"
Add-Content $outputFile "					(js.job_id = ja.job_id)"
Add-Content $outputFile "					AND (js.step_id = ja.last_executed_step_id)"
Add-Content $outputFile "				LEFT JOIN msdb.dbo.sysjobhistory AS jh ON"
Add-Content $outputFile "					(jh.job_id = j.job_id)"
Add-Content $outputFile "					AND (jh.instance_id = ja.job_history_id)"
Add-Content $outputFile "				WHERE j.name = @jobName"
Add-Content $outputFile "				ORDER BY ja.start_execution_date DESC"
Add-Content $outputFile "			);"
Add-Content $outputFile ""
Add-Content $outputFile "			IF (@installationJobExecuting = 'Running')"
Add-Content $outputFile "			BEGIN"
Add-Content $outputFile "				SET @installationWaitCnt = @installationWaitCnt + 1;"
Add-Content $outputFile ""
Add-Content $outputFile "				SET @installationNow = GETDATE();"
Add-Content $outputFile "				SET @installationNowStr = CONVERT(nvarchar, @installationNow, 126);"
Add-Content $outputFile "				SET @installationNowStr = REPLACE(LEFT(@installationNowStr, LEN(@installationNowStr) - 4), 'T', ' ');"
Add-Content $outputFile ""
Add-Content $outputFile "				SET @installationMsg = '  Waiting for job ' + QUOTENAME(@jobName) + ' to stop executing - #:' + CAST(@installationWaitCnt AS nvarchar) + ' - ' + @installationNowStr;"
Add-Content $outputFile "				RAISERROR(@installationMsg, 0, 1) WITH NOWAIT;"
Add-Content $outputFile ""
Add-Content $outputFile "				WAITFOR DELAY '00:00:05';"
Add-Content $outputFile "			END;"
Add-Content $outputFile "		END;"
Add-Content $outputFile "	END;"
Add-Content $outputFile ""
Add-Content $outputFile "	CLOSE jCur;"
Add-Content $outputFile "	DEALLOCATE jCur;"
Add-Content $outputFile "END;"
Add-Content $outputFile ""
Add-Content $outputFile "--"
Add-Content $outputFile "-- Rename key for AgentJobName, and the job and schedules names when upgrading from versions before 2.12"
Add-Content $outputFile "--"
Add-Content $outputFile "IF (@installUpgradeFlag = 2)"
Add-Content $outputFile "BEGIN"
Add-Content $outputFile "	SET @stmt = '"
Add-Content $outputFile "		USE ' + QUOTENAME(@fhSQLMonitorDatabase) + ';"
Add-Content $outputFile ""
Add-Content $outputFile "		SET @jobName = NULL;"
Add-Content $outputFile ""
Add-Content $outputFile "		IF EXISTS ("
Add-Content $outputFile "			SELECT *"
Add-Content $outputFile "			FROM dbo.fhsmConfigurations AS c"
Add-Content $outputFile "			WHERE (c.[Key] = ''AgentJobName'')"
Add-Content $outputFile "		)"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			UPDATE c"
Add-Content $outputFile "			SET c.[Key] = ''AgentJobName0''"
Add-Content $outputFile "			FROM dbo.fhsmConfigurations AS c"
Add-Content $outputFile "			WHERE (c.[Key] = ''AgentJobName'');"
Add-Content $outputFile ""
Add-Content $outputFile "			SET @jobName = ("
Add-Content $outputFile "				SELECT c.Value"
Add-Content $outputFile "				FROM dbo.fhsmConfigurations AS c"
Add-Content $outputFile "				WHERE (c.[Key] = ''AgentJobName0'')"
Add-Content $outputFile "			);"
Add-Content $outputFile ""
Add-Content $outputFile "			IF EXISTS("
Add-Content $outputFile "				SELECT *"
Add-Content $outputFile "				FROM msdb.dbo.sysjobs AS sj"
Add-Content $outputFile "				WHERE (sj.name = @jobName)"
Add-Content $outputFile "			)"
Add-Content $outputFile "			BEGIN"
Add-Content $outputFile "				EXEC msdb.dbo.sp_update_job @job_name = @jobName, @new_name = @new_name;"
Add-Content $outputFile ""
Add-Content $outputFile "				UPDATE c"
Add-Content $outputFile "				SET c.Value = @new_name"
Add-Content $outputFile "				FROM dbo.fhsmConfigurations AS c"
Add-Content $outputFile "				WHERE (c.[Key] = ''AgentJobName0'');"
Add-Content $outputFile "			END;"
Add-Content $outputFile ""
Add-Content $outputFile "			IF EXISTS("
Add-Content $outputFile "				SELECT *"
Add-Content $outputFile "				FROM msdb.dbo.sysschedules AS ss"
Add-Content $outputFile "				WHERE (ss.name = @jobName)"
Add-Content $outputFile "			)"
Add-Content $outputFile "			BEGIN"
Add-Content $outputFile "				EXEC msdb.dbo.sp_update_schedule @name = @jobName, @new_name = @new_name;"
Add-Content $outputFile ""
Add-Content $outputFile "				IF EXISTS("
Add-Content $outputFile "					SELECT *"
Add-Content $outputFile "					FROM msdb.dbo.sysschedules AS ss"
Add-Content $outputFile "					WHERE (ss.name = @new_name)"
Add-Content $outputFile "						AND (ss.freq_type = 4)"
Add-Content $outputFile "						AND (ss.freq_interval = 1)"
Add-Content $outputFile "						AND (ss.freq_subday_type = 2)"
Add-Content $outputFile "						AND (ss.freq_subday_interval = 30)"
Add-Content $outputFile "						AND (ss.freq_relative_interval = 0)"
Add-Content $outputFile "						AND (ss.freq_recurrence_factor = 0)"
Add-Content $outputFile "				)"
Add-Content $outputFile "				BEGIN"
Add-Content $outputFile "					EXEC msdb.dbo.sp_update_schedule"
Add-Content $outputFile "						@name = @new_name"
Add-Content $outputFile "						,@freq_subday_interval = 60;"
Add-Content $outputFile "				END;"
Add-Content $outputFile "			END;"
Add-Content $outputFile "		END;"
Add-Content $outputFile "	';"
Add-Content $outputFile "	EXEC sp_executesql"
Add-Content $outputFile "		@stmt,"
Add-Content $outputFile "		N'@jobName sysname OUTPUT, @new_name sysname',"
Add-Content $outputFile "		@jobName = @jobName OUTPUT,"
Add-Content $outputFile "		@new_name = @fhsqlAgentJobNameType0;"
Add-Content $outputFile ""
Add-Content $outputFile "	IF (@jobName IS NOT NULL)"
Add-Content $outputFile "	BEGIN"
Add-Content $outputFile "		UPDATE j"
Add-Content $outputFile "		SET j.JobName = @fhsqlAgentJobNameType0"
Add-Content $outputFile "		FROM @jobs AS j"
Add-Content $outputFile "		WHERE (j.JobName = @jobName);"
Add-Content $outputFile ""
Add-Content $outputFile "		INSERT INTO @jobs(JobName, JobStatus)"
Add-Content $outputFile "		SELECT @fhsqlAgentJobNameType1, j.JobStatus"
Add-Content $outputFile "		FROM @jobs AS j"
Add-Content $outputFile "		WHERE (j.JobName = @fhsqlAgentJobNameType0)"
Add-Content $outputFile "			AND NOT EXISTS (SELECT * FROM @jobs AS j WHERE (j.JobName = @fhsqlAgentJobNameType1));"
Add-Content $outputFile "	END;"
Add-Content $outputFile "END;"

$filenames = Get-Content InstallationFileNames.txt
foreach ($file in $filenames) {
    echo $file

    $fileItem = Get-Item $file
    $fileLastWriteTimeStr = ($fileItem.LastWriteTime).ToString("yyyy:MM:dd HH:mm:ss")

    $content = Get-Content $file -Raw
    $content = $content.Replace('''', '''''')

    Add-Content $outputFile ""
    Add-Content $outputFile "--"
    Add-Content $outputFile ("-- File part:" + $file + " modified: " + $fileLastWriteTimeStr)
    Add-Content $outputFile "--"

    Add-Content $outputFile "SET @stmt = '"

    if ($file -ne "_Install-FHSQLMonitor.sql") {
        Add-Content $outputFile "USE ' + QUOTENAME(@fhSQLMonitorDatabase) + ';"
    }

    Add-Content $outputFile $content
    Add-Content $outputFile "';"

    if ($file -eq "_Install-FHSQLMonitor.sql") {
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @createSQLAgentJobs = 1;',                               'SET @createSQLAgentJobs = ' + CAST(@createSQLAgentJobs AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @fhSQLMonitorDatabase = ''FHSQLMonitor'';',              'SET @fhSQLMonitorDatabase = ''' + @fhSQLMonitorDatabase + ''';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @fhsqlAgentJobNameType0 = ''FHSQLMonitor type 0 in FHSQLMonitor'';', 'SET @fhsqlAgentJobNameType0 = ''' + @fhsqlAgentJobNameType0 + ''';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @fhsqlAgentJobNameType1 = ''FHSQLMonitor type 1 in FHSQLMonitor'';', 'SET @fhsqlAgentJobNameType1 = ''' + @fhsqlAgentJobNameType1 + ''';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @pbiSchema = ''FHSM'';',                                 'SET @pbiSchema = ''' + @pbiSchema + ''';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @buildTimeStr = ''YYYY-MM-DD HH:MM:SS'';',               'SET @buildTimeStr = ''$buildTimeStr'';');"
    } else {
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @blocksAndDeadlocksFilePath = NULL;', 'SET @blocksAndDeadlocksFilePath = ' + COALESCE('''' + CAST(@blocksAndDeadlocksFilePath AS nvarchar(260)) + '''', 'NULL') + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @olaDatabase = NULL;', 'SET @olaDatabase = ' + COALESCE('''' + CAST(@olaDatabase AS nvarchar(128)) + '''', 'NULL') + ';');"
        Add-Content $outputFile ""
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @ignoreAutoIndex = 0;',                'SET @ignoreAutoIndex = 1;');"
        Add-Content $outputFile ""
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableAgentJobs = 0;',                'SET @enableAgentJobs = '                + CAST(@enableAgentJobs AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableAgentJobsPerformance = 0;',     'SET @enableAgentJobsPerformance = '     + CAST(@enableAgentJobsPerformance AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableAgeOfStatistics = 0;',          'SET @enableAgeOfStatistics = '          + CAST(@enableAgeOfStatistics AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableBackupStatus = 0;',             'SET @enableBackupStatus = '             + CAST(@enableBackupStatus AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableBlocksAndDeadlocks = 0;',       'SET @enableBlocksAndDeadlocks = '       + CAST(@enableBlocksAndDeadlocks AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableCapacity = 0;',                 'SET @enableCapacity = '                 + CAST(@enableCapacity AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableConnections = 0;',              'SET @enableConnections = '              + CAST(@enableConnections AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableCPUUtilization = 0;',           'SET @enableCPUUtilization = '           + CAST(@enableCPUUtilization AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableDatabaseIO = 0;',               'SET @enableDatabaseIO = '               + CAST(@enableDatabaseIO AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableDatabaseState = 0;',            'SET @enableDatabaseState = '            + CAST(@enableDatabaseState AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableIndexOperational = 0;',         'SET @enableIndexOperational = '         + CAST(@enableIndexOperational AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableIndexPhysical = 0;',            'SET @enableIndexPhysical = '            + CAST(@enableIndexPhysical AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableIndexUsage = 0;',               'SET @enableIndexUsage = '               + CAST(@enableIndexUsage AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableInstanceState = 0;',            'SET @enableInstanceState = '            + CAST(@enableInstanceState AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableLogShipping = 0;',              'SET @enableLogShipping = '              + CAST(@enableLogShipping AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableMemory = 0;',                   'SET @enableMemory = '                   + CAST(@enableMemory AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableMissingIndexes = 0;',           'SET @enableMissingIndexes = '           + CAST(@enableMissingIndexes AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enablePerformanceStatistics = 0;',    'SET @enablePerformanceStatistics = '    + CAST(@enablePerformanceStatistics AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enablePlanCacheUsage = 0;',           'SET @enablePlanCacheUsage = '           + CAST(@enablePlanCacheUsage AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enablePlanGuides = 0;',               'SET @enablePlanGuides = '               + CAST(@enablePlanGuides AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableQueryStatistics = 0;',          'SET @enableQueryStatistics = '          + CAST(@enableQueryStatistics AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableTriggers = 0;',                 'SET @enableTriggers = '                 + CAST(@enableTriggers AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableWaitStatistics = 0;',           'SET @enableWaitStatistics = '           + CAST(@enableWaitStatistics AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableWhoIsActive = 0;',              'SET @enableWhoIsActive = '              + CAST(@enableWhoIsActive AS nvarchar) + ';');"

        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableIndexRebuild = 0;',             'SET @enableIndexRebuild = '             + CAST(@enableIndexRebuild AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableIndexReorganize = 0;',          'SET @enableIndexReorganize = '          + CAST(@enableIndexReorganize AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableUpdateAllStatistics = 0;',      'SET @enableUpdateAllStatistics = '      + CAST(@enableUpdateAllStatistics AS nvarchar) + ';');"
        Add-Content $outputFile "SET @stmt = REPLACE(@stmt, 'SET @enableUpdateModifiedStatistics = 0;', 'SET @enableUpdateModifiedStatistics = ' + CAST(@enableUpdateModifiedStatistics AS nvarchar) + ';');"
    }

    Add-Content $outputFile "EXEC(@stmt);"
}

Add-Content $outputFile ""
Add-Content $outputFile "--"
Add-Content $outputFile "-- Creating auto indexes"
Add-Content $outputFile "--"
Add-Content $outputFile "BEGIN"
Add-Content $outputFile "	RAISERROR('', 0, 1) WITH NOWAIT;"
Add-Content $outputFile "	SET @installationMsg = 'Creating auto indexes';"
Add-Content $outputFile "	RAISERROR(@installationMsg, 0, 1) WITH NOWAIT;"
Add-Content $outputFile ""
Add-Content $outputFile "	SET @stmt = '"
Add-Content $outputFile "		USE ' + QUOTENAME(@fhSQLMonitorDatabase) + ';"
Add-Content $outputFile ""
Add-Content $outputFile "		EXEC dbo.fhsmSPUpdateDimensions;"
Add-Content $outputFile "	';"
Add-Content $outputFile "	EXEC(@stmt);"
Add-Content $outputFile "END;"

Add-Content $outputFile ""
Add-Content $outputFile "--"
Add-Content $outputFile "-- Enable jobs again if they were enabled when we started"
Add-Content $outputFile "--"
Add-Content $outputFile "BEGIN"
Add-Content $outputFile "	DECLARE jCur CURSOR LOCAL READ_ONLY FAST_FORWARD FOR"
Add-Content $outputFile "	SELECT j.JobName, j.JobStatus"
Add-Content $outputFile "	FROM @jobs AS j"
Add-Content $outputFile "	ORDER BY j.JobName;"
Add-Content $outputFile ""
Add-Content $outputFile "	OPEN jCur;"
Add-Content $outputFile ""
Add-Content $outputFile "	WHILE (1 = 1)"
Add-Content $outputFile "	BEGIN"
Add-Content $outputFile "		FETCH NEXT FROM jCur"
Add-Content $outputFile "		INTO @jobName, @jobStatus;"
Add-Content $outputFile ""
Add-Content $outputFile "		IF (@@FETCH_STATUS <> 0)"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			BREAK;"
Add-Content $outputFile "		END;"
Add-Content $outputFile ""
Add-Content $outputFile "		IF (@jobName = 'FHSQLMonitor in FHSQLMonitor')"
Add-Content $outputFile "			AND NOT EXISTS ("
Add-Content $outputFile "				SELECT *"
Add-Content $outputFile "				FROM msdb.dbo.sysjobs AS sj"
Add-Content $outputFile "				WHERE (sj.name = 'FHSQLMonitor in FHSQLMonitor')"
Add-Content $outputFile "			)"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			SET @jobName = 'FHSQLMonitor type 0 in FHSQLMonitor';"
Add-Content $outputFile "		END;"
Add-Content $outputFile ""
Add-Content $outputFile "		IF (@jobStatus = 1)"
Add-Content $outputFile "		BEGIN"
Add-Content $outputFile "			RAISERROR('', 0, 1) WITH NOWAIT;"
Add-Content $outputFile "			SET @installationMsg = 'Enabling job ' + QUOTENAME(@jobName);"
Add-Content $outputFile "			RAISERROR(@installationMsg, 0, 1) WITH NOWAIT;"
Add-Content $outputFile ""
Add-Content $outputFile "			EXEC msdb.dbo.sp_update_job"
Add-Content $outputFile "				@job_name = @jobName,"
Add-Content $outputFile "				@enabled = 1;"
Add-Content $outputFile "		END;"
Add-Content $outputFile "	END;"
Add-Content $outputFile ""
Add-Content $outputFile "	CLOSE jCur;"
Add-Content $outputFile "	DEALLOCATE jCur;"
Add-Content $outputFile "END;"
Add-Content $outputFile ""
Add-Content $outputFile "RAISERROR('', 0, 1) WITH NOWAIT;"
Add-Content $outputFile ("SET @installationMsg = 'FHSQLMonitor in database ' + @fhSQLMonitorDatabase + ' on ' + @serverInfo + ' has been ' + CASE @installUpgradeFlag WHEN 1 THEN 'installed with' ELSE 'upgraded to' END + ' " + $versionNumber + "';")
Add-Content $outputFile "RAISERROR(@installationMsg, 0, 1) WITH NOWAIT;"
